---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: v1-validator1  # +operator-builder:field:parent=metadata.name,type=string
  namespace: default # +operator-builder:collection:field:parent=metadata.name,type=string
spec:
  selector:
    matchLabels:
      app: v1-validator1  # +operator-builder:field:parent=metadata.name,type=string
  serviceName: v1-validator1  # +operator-builder:field:parent=metadata.name,type=string
  replicas: 1  # +operator-builder:field:name=validatorReplicas,type=int,default=1
  template:
    metadata:
      labels:
        app: v1-validator1  # +operator-builder:field:parent=metadata.name,type=string
        v1-purpose: validator
    spec:
      containers:
        - name: pocket
          image: poktnetwork/pocket-v1:main-dev  # +operator-builder:field:name=pocketImage,type=string
          args:
            - pocket
            - -config=/configs/config.json
          ports:
            - containerPort: 8221
              name: pre2p
            - containerPort: 8222
              name: p2p
          volumeMounts:
            - name: config-volume
              mountPath: /configs
            - name: genesis-volume
              mountPath: /genesis.json
              subPath: genesis.json
            - name: name-blockstore  # +operator-builder:field:parent=metadata.name,replace="name",type=string
              mountPath: /blockstore
      volumes:
        - name: config-volume
          configMap:
            name: name-config  # +operator-builder:field:parent=metadata.name,replace="name",type=string
        - name: genesis-volume
          configMap:
            name: name-genesis  # +operator-builder:collection:field:parent=metadata.name,replace="name",type=string
  volumeClaimTemplates:
    - metadata:
        name: name-blockstore  # +operator-builder:field:parent=metadata.name,replace="name",type=string
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: v1-validator1  # +operator-builder:field:parent=metadata.name,type=string
  namespace: default # +operator-builder:collection:field:parent=metadata.name,type=string
  labels:
    app: v1-validator1  # +operator-builder:field:parent=metadata.name,type=string
spec:
  ports:
    - port: 8221
      name: pre2p
    - port: 8222
      name: p2p
  selector:
    app: v1-validator1  # +operator-builder:field:parent=metadata.name,type=string
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: name-config  # +operator-builder:field:parent=metadata.name,type=string,replace="name"
  namespace: default # +operator-builder:collection:field:parent=metadata.name,type=string
data:
  # +operator-builder:field:name=privateKey,type=string,replace="privatekey"
  # +operator-builder:field:name=peers,type=string,replace="nodePeers"
  # +operator-builder:field:parent=metadata.name,type=string,replace="dbservice"
  config.json: |
    {
      "root_dir": "/data",
      "genesis_source": {
        "file": {
          "path": "/genesis.json"
        }
      },
      "private_key": "privatekey",
      "enable_telemetry": true,
      "p2p": {
        "consensus_port": 8221,
        "use_raintree": true,
        "connection_type": "tcp",
        "protocol": "tcp",
        "address": "0.0.0.0:8222",
        "peers": [ "nodePeers" ]
      },
      "consensus": {
        "max_mempool_bytes": 500000000,
        "max_block_bytes": 4000000,
        "pacemaker": {
          "timeout_msec": 5000,
          "manual": true,
          "debug_time_between_steps_msec": 1000
        }
      },
      "pre_persistence": {
        "capacity": 99999,
        "mempool_max_bytes": 99999,
        "mempool_max_txs": 99999
      },
      "persistence": {
        "postgres_url": "postgres://validator:postgres@dbservice-database:5432/validatordb",
        "schema": "validator",
        "block_store_path": "/blockstore"
      },
      "utility": {},
      "telemetry": {
        "address": "0.0.0.0:9000",
        "endpoint": "/metrics"
      }
    }

