apiVersion: v1
kind: Service
metadata:
  name: name-validators  # +operator-builder:field:parent=metadata.name,type=string,replace="name"
  namespace: default # +operator-builder:field:parent=metadata.name,type=string
spec:
  ports:
    - port: 8221
      name: pre2p
    - port: 8222
      name: p2p
  clusterIP: None
  selector:
    v1-purpose: validator
