# permissions for end users to view pocketsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pocketset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pocket-operator
    app.kubernetes.io/part-of: pocket-operator
    app.kubernetes.io/managed-by: kustomize
  name: pocketset-viewer-role
rules:
- apiGroups:
  - nodes.pokt.network
  resources:
  - pocketsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodes.pokt.network
  resources:
  - pocketsets/status
  verbs:
  - get
