# permissions for end users to edit pocketsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pocketset-editor-role
rules:
- apiGroups:
  - nodes.pokt.network
  resources:
  - pocketsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodes.pokt.network
  resources:
  - pocketsets/status
  verbs:
  - get
