# permissions for end users to view pocketsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pocketset-viewer-role
rules:
- apiGroups:
  - nodes.pokt.network
  resources:
  - pocketsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodes.pokt.network
  resources:
  - pocketsets/status
  verbs:
  - get
