apiVersion: nodes.pokt.network/v1alpha1
kind: PocketValidator
metadata:
  name: v1-validator4
spec:
  collection:
    name: "primary"
  validatorReplicas: 1
  dbReplicas: 1
  pocketImage: "poktnetwork/pocket-v1:sha-2cd775d-dev"
  privateKey: "ddff03df6c525e551c5e9cd0e31ac4ec99dd6aa5d62185ba969bbf2e62db7e2c6c207cea1b1bf45dad8f8973d57291d3da31855254d7f1ed83ec3e06cabfe6b7"
