apiVersion: nodes.pokt.network/v1alpha1
kind: PocketValidator
metadata:
  name: v1-validator3
spec:
  collection:
    name: "primary"
  validatorReplicas: 1
  dbReplicas: 1
  pocketImage: "poktnetwork/pocket-v1:sha-2cd775d-dev"
  privateKey: "c7bd1bd027e76b31534c3f5226c8e3c3f2a034ba9fa11017b65191f7f9ef0d253e5e4bbed5f98721163bb84445072a9202d213f1e348c5e9e0e2ea83bbb7e3aa"
