apiVersion: nodes.pokt.network/v1alpha1
kind: PocketValidator
metadata:
  name: v1-validator1
spec:
  collection:
    name: "primary"
  validatorReplicas: 1
  dbReplicas: 1
  pocketImage: "poktnetwork/pocket-v1:sha-2cd775d-dev"
  privateKey: "ccec19df8fe866280e41da68d52d0ecdb07b01e85eeef45f400fd3a89b71c26a79254a4bc46bf1182826145b0b01b48bab4240cd30e23ba90e4e5e6b56961c6d"
