apiVersion: nodes.pokt.network/v1alpha1
kind: PocketValidator
metadata:
  name: v1-validator2
spec:
  collection:
    name: "primary"
  validatorReplicas: 1
  # TODO: once we have this available via envar, make a secretRef
  postgres_url: postgres://validator:EgSGBwwdcy4CWg5Oy8VxsFg1Yd2INukyr1xyvBKeTagxH0zeciq34SBy1IPCNdmm@pocket-database:5432/validatordb
  postgres_schema: validator2
  pocketImage: "ghcr.io/pokt-network/pocket-v1:sha-87a6060-dev"
  privateKey: "b37d3ba2f232060c41ba1177fea6008d885fcccad6826d64ee7d49f94d1dbc49a8b6be75d7551da093f788f7286c3a9cb885cfc8e52710eac5f1d5e5b4bf19b2"
