apiVersion: nodes.pokt.network/v1alpha1
kind: PocketValidator
metadata:
  name: v1-validator4
spec:
  collection:
    name: "primary"
  validatorReplicas: 1
  # TODO: once we have this available via envar, make a secretRef
  postgres_url: postgres://validator:EgSGBwwdcy4CWg5Oy8VxsFg1Yd2INukyr1xyvBKeTagxH0zeciq34SBy1IPCNdmm@pocket-database:5432/validatordb
  postgres_schema: validator4
  pocketImage: "ghcr.io/pokt-network/pocket-v1:sha-87a6060-dev"
  privateKey: "c6c136d010d07d7f5e9944aa3594a10f9210dd3e26ebc1bc1516a6d957fd0df353ee26c82826694ffe1773d7b60d5f20dd9e91bdf8745544711bec5ff9c6fb4a"
